name: Continuous Integration

on:
  workflow_dispatch:
    inputs:
      test_node_24:
        description: 'Test on Node.js 24.x'
        required: false
        default: true
        type: boolean
      run_security_audit:
        description: 'Run security audit'
        required: false
        default: true
        type: boolean
      audit_level:
        description: 'Security audit level'
        required: false
        default: 'moderate'
        type: choice
        options:
        - low
        - moderate
        - high
        - critical

jobs:
  test-node-24:
    runs-on: ubuntu-latest
    if: ${{ inputs.test_node_24 }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '24.x'
          cache: npm
          cache-dependency-path: package-lock.json

      - run: npm ci
      - run: npm run lint
      - run: npx tsc --noEmit
      - run: npm run build
      - run: |
          echo "✅ Build completed successfully on Node.js 24.x"
          du -sh dist/
          ls -la dist/

  security:
    runs-on: ubuntu-latest
    if: ${{ inputs.run_security_audit }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: package-lock.json

      - run: npm ci
      - run: npm audit --audit-level=${{ inputs.audit_level || 'moderate' }} --production
