name: Continuous Integration

on:
  workflow_dispatch:
    inputs:
      test_node_18:
        description: 'Test on Node.js 18.x'
        required: false
        default: true
        type: boolean
      test_node_20:
        description: 'Test on Node.js 20.x'
        required: false
        default: true
        type: boolean
      run_security_audit:
        description: 'Run security audit'
        required: false
        default: true
        type: boolean
      audit_level:
        description: 'Security audit level'
        required: false
        default: 'moderate'
        type: choice
        options:
        - low
        - moderate
        - high
        - critical

jobs:
  test-node-18:
    runs-on: ubuntu-latest
    if: ${{ inputs.test_node_18 }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Type check
        run: npx tsc --noEmit

      - name: Build project
        run: npm run build

      - name: Check build size
        run: |
          echo "Build completed successfully on Node.js 18.x!"
          du -sh dist/
          echo "Build artifacts:"
          ls -la dist/

  test-node-20:
    runs-on: ubuntu-latest
    if: ${{ inputs.test_node_20 }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Type check
        run: npx tsc --noEmit

      - name: Build project
        run: npm run build

      - name: Check build size
        run: |
          echo "Build completed successfully on Node.js 20.x!"
          du -sh dist/
          echo "Build artifacts:"
          ls -la dist/

  security:
    runs-on: ubuntu-latest
    if: ${{ inputs.run_security_audit }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run security audit
        run: npm audit --audit-level=${{ inputs.audit_level || 'moderate' }}

      - name: Check for vulnerabilities (production only)
        run: npm audit --audit-level=${{ inputs.audit_level || 'moderate' }} --production