name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
        - production
        - staging
      skip_tests:
        description: 'Skip linting and tests'
        required: false
        default: false
        type: boolean

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: package-lock.json

      - run: npm ci

      - name: Lint code
        if: ${{ github.event_name == 'workflow_dispatch' && !inputs.skip_tests }}
        run: npm run lint

      - name: Type check
        if: ${{ github.event_name == 'workflow_dispatch' && !inputs.skip_tests }}
        run: npx tsc --noEmit

      - name: Build project
        run: npm run build
        env:
          NODE_ENV: ${{ github.event.inputs.environment || 'production' }}

      - name: Add .nojekyll file
        run: touch dist/.nojekyll

      - name: Add SPA fallback (404.html)
        run: cp dist/index.html dist/404.html

      - uses: actions/configure-pages@v4

      - uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
