name: Pull Request Validation

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Pull Request number to validate'
        required: true
        type: string
      full_test_suite:
        description: 'Run full test suite including security audit'
        required: false
        default: true
        type: boolean

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ inputs.pr_number }}/head

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Type check
        run: npx tsc --noEmit

      - name: Build project
        run: npm run build

      - name: Security audit
        if: ${{ inputs.full_test_suite }}
        run: npm audit --audit-level=moderate

      - name: Check build artifacts
        run: |
          echo "Build completed successfully!"
          du -sh dist/
          echo "Build artifacts:"
          ls -la dist/

      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: ${{ inputs.pr_number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ Manual validation completed successfully!\n\n- Linting: Passed\n- Type checking: Passed\n- Build: Passed\n- Security audit: ${{ inputs.full_test_suite && "Passed" || "Skipped" }}'
            })